# Title: Christman-composers.yaml
# Author: Professor Krasso
# Date: June 10, 2023
# Modified By: Michael Christman
# Description: Assignment 3.2 Describing the Composer API

openapi: "3.0.0"
info:
  title: Composer API
  version: "1.0"
paths: 
  /composers:
    description: Return the output of the list of Composers
    get: 
      summary: View the full list of composers from MongoDB
      tags: 
        - Composers
      responses: 
        "200":
          description: Composer Documents
        "500":
          description: Server Exception
        "501":
          description: MongoDB Exception
    post:
      summary: Add a new composer object to the list of composers
      tags: 
        - Composers
      requestBody:
        description: Composer's Information
        content:
          application/json:
            schema:
              required:
                - firstName
                - lastName
              properties:
                firstName: 
                  type: string
                lastName:
                  type: string
      responses:
        "200":
          description: Composer Added
        "500":
          description: Server Exception
        "501":
          description: MongoDB Exception
  /composers/{id}:
    description: Find a single Composer object through path 
    parameters: 
      - name: id
        description: Composer ID Requested by User
        in: path
        required: true
        schema:
          type: string
    get:
      summary: Search for Composer Object
      tags: 
        - Composers
      description: Returns an output for a single Composer object from MongoDB
      responses: 
        "200":
          description: Composer Document in JSON
        "500":
          description: Server Exception
        "501":
          description: MongoDB Exception
