openapi: "3.10.0"
info:
  title: FindByComposerId 
  version: 1.0.0
paths:
  /find/{id}:
    get:
      tags:
        - YAML Examples
      description: API for returning a single document from MongoDB.
      summary: returns a single document.
      parameters:
        - name: id
          in: path
          required: true
          description: Id to filter the collection by.
          schema:
            type: string
      responses:
        '200':
          description: MongoDB Document
        '500':
          description: Server Exception
        '501':
          description: MongoDB Exception
